/************************************************************************** 
* Verity TI
* --------------------------- 
* Criado por...:           Guilherme de Oliveira
* Em...........:           03/07/2017
* Projeto......:           Prosperity
* Descrição....:           Script para preenchimento das tabelas do banco Prosperity
* Tabelas envoldidas:      Tabela de dominio
**************************************************************************/ 

DECLARE @nomeScript VARCHAR(MAX);
SET @nomeScript = '01. nome do script aqui'
PRINT 'Iniciando execução script ['+ @nomeScript +']'
BEGIN TRY
    BEGIN TRANSACTION;

		USE [Prosperity]

		INSERT INTO [dbo].[tbAvaliacao]
				   ([nmAvaliacao]
				   ,[tpCss])
			 VALUES
				   ('Insatisfatório' ,'#F51D17'),
				   ('Em desenvolvimento' ,'#FF8E00'),
				   ('Atende as expectativas' ,'#FEBF10'),
				   ('Supera as expectativas' ,'#78DE19'),
				   ('Não informar' ,'#B5B5B5')

		INSERT INTO [dbo].[tbCanalInformacao]
				   (nmCanalInformacao)
			 VALUES
				   ('Site Verity'),
				   ('Facebook'),
				   ('Linkedin'),
				   ('Apinfo'),
				   ('Catho'),
				   ('Outros sites de oportunidades'),
				   ('Indicação de colegas'),
				   ('Outros')

		INSERT INTO [dbo].[tbCancelamento]
				   (dsCancelamento)
			 VALUES
				   ('Fora do perfil'),
				   ('Declinou'),
				   ('Sem interesse'),
				   ('Stand by')

		INSERT INTO [dbo].[tbCargo]
				   (nmCargo)
			 VALUES
				   ('Administrativo Telecom'),
				   ('Analista de BI'),
				   ('Analista de Configuração'),
				   ('Analista de Infraestrutura'),
				   ('Analista de Marketing'),
				   ('Analista de Negócio'),
				   ('Analista de Processos'),
				   ('Analista de Recursos Humanos'),
				   ('Analista de Requisitos'),
				   ('Analista de Sistemas'),
				   ('Analista de Suporte'),
				   ('Analista de Teste'),
				   ('Analista Desenvolvedor'),
				   ('Analista Desenvolvedor Java'),
				   ('Analista Financeiro'),
				   ('Analista Funcional'),
				   ('Analista Telecom'),
				   ('Arquiteto'),
				   ('Arquiteto de Sistemas'),
				   ('Arquiteto de Soluções'),
				   ('Arquiteto IOS'),
				   ('Assistente Administrativo'),
				   ('Assistente Comercial'),
				   ('Assistente de Recursos Humanos'),
				   ('Assistente Depto Pessoal'),
				   ('Auxiliar de Seriços Gerais'),
				   ('Banco de talentos Analista de Sistemas'),
				   ('Banco de talentos Administrativo e Financeiro'),
				   ('Banco de talentos Gestão de Configuração'),
				   ('Banco de talentos de Infraestrutura'),
				   ('Banco de Talentos Recursos Humanos '),
				   ('Banco de Taletos'),
				   ('Cargo Temp Integração PSOffice'),
				   ('Consultor'),
				   ('Consultor Especialista Digital'),
				   ('Coordenadora de Recursos Humanos'),
				   ('Desenvolvedor'),
				   ('Desenvolvedor .NET'),
				   ('Desenvolvedor Java'),
				   ('Diretor'),
				   ('Especialista de Cobrança'),
				   ('Estagiário'),
				   ('Gerente Comercial'),
				   ('Gerente de Configuração'),
				   ('Gerente de Parcerias e Estratégias'),
				   ('Gerente de Projetos'),
				   ('Gerente de Soluções Digitais'),
				   ('Gerente de Operações'),
				   ('Gestor de Projetos'),
				   ('Gestor de teste'),
				   ('Líder de Configuração'),
				   ('Líder de Projetos'),
				   ('Líder de Sustentação'),
				   ('Líder de Teste'),
				   ('Líder de Financeiro'),
				   ('Líder de Técnico'),
				   ('Motorista'),
				   ('Plantonista Técnico'),
				   ('Programador'),
				   ('Programador ASP'),
				   ('Programador Mobile Jr'),
				   ('Programador Sharepoint'),
				   ('Scrum Master'),
				   ('Secretária')
				   

		INSERT INTO [dbo].[tbSenioridade]
				   (nmSenioridade)
			 VALUES
				   ('Junior'),
				   ('Pleno'),
				   ('Senior'),
				   ('A definir')

		INSERT INTO [dbo].[tbCliente]
				   (nmCliente)
			 VALUES
					('SulAmérica - Geração de E-mail Marketing'),
					('P20131203_005 - Loadbridge'),
					('3D Secure'),
					('Consultoria de Processo de Desenvolvimento e Teste de Software'),
					('P20130628_002 - Zoetis - Sustentação - Fase 2 Operação'),
					('Nova URA'),
					('P20130912_007 - Fábrica de Teste Makro - Fase Operação(antigo)'),
					('Novo Cartão Funcionário'),
					('P20130711_001 - Novo Fluxo de Propostas'),
					('P20130701_001 - Atualização Tecnológica'),
					('Projeto Zurich - A'),
					('Projeto Wal-Mart - A'),
					('Ajustes SUSEP'),
					('P20140305_003 - Nova Solução de Cobrança'),
					('P20140225_001 - Novo Fluxo Alteração de Limite'),
					('P20130712_001 - Novo Portal de Cartões ( Construção e Implantação )'),
					('C20120917_001 - Novo Portal de Cartões ( Concepção e Análise Funcional)'),
					('P20130715_001 - Novo Portal Cartões - Frente de Testes'),
					('Redução de Campos na Proposta'),
					('Melhorias Cartão Funcionário'),
					('Front Único - Mobile'),
					('Melhorias Front Única 26/5'),
					('Projeto - Alocação VB6 - Tempo Assist'),
					('Projeto Sky - A'),
					('Projeto Netpoints - A'),
					('Projeto Carrefour - A'),
					('Melhorias Identificação Positiva'),
					('Melhorias Antecipação de Recebíveis'),
					('P20140331_001 - Cadastro 1ª Senha do Cartão'),
					('Ajuste no Empréstimo da Paytrue'),
					('Opt in Opt Avaliação Emergencial de Crédito'),
					('Projeto Novo Portal - Fase 3'),
					('Processos Verity _ 2014'),
					('Banco Carrefour - Anuidade'),
					('Blindagem CPF - Full'),
					('Overlimit - Fase 3'),
					('Projeto Banco Rendimento - A'),
					('Projeto Interno 22'),
					('Alocação Walmart - 20160620-001'),
					('WALMART20131003-v2-Gerente-de-Projetos'),
					('WALMART20140702-v2-Desenvolvedor-Senior'),
					('ZURICH20130116-v1'),
					('Obrigatoriedade CPF Adicional'),
					('Melhorias Help Online'),
					('O20140416_001 - CSF Sustentação - Suporte a Produção(antigo)'),
					('WALMART20140722-Desenvolvedor-Senior'),
					('Banco Carrefour - Novo Modelo de Autorizador'),
					('P20140609_001 - Pin Validation'),
					('NovoPortal_QA'),
					('Atualização Tecnológica'),
					('A20121220 - Profissionais sem alocação - Custo Verity'),
					('Desenvolvimento Liferay'),
					('Home Delivey'),
					('Formulário de Leads'),
					('Picasso'),
					('Website Institucional'),
					('P20140731_001 - Componente de Mensageria'),
					('Melhorias Taxas e Tarifas'),
					('Globo - Plataforma de publicidade'),
					('Carenet'),
					('BRMS.IO'),
					('WBTEC'),
					('MetaCrédito'),
					('Agilize - Projeto para Agilizar'),
					('ProImobi'),
					('Med.Net'),
					('Me.IO'),
					('Crounders'),
					('Atendimento Ágil'),
					('GeoIT'),
					('P20140902_001 - Projeto VPF Qualidade e Teste do Sistema de Programação de Cin'),
					('Histórico de Manutenções Cadastrais_2'),
					('Programa de Pontos Beauty Club'),
					('Nova Solução Termos'),
					('PROBE - FASE2B'),
					('P20140915_002 - CSF - Administrativo'),
					('Probe Fase 2B ( Variáveis Externas)'),
					('Pré-venda RFP Bonificação Antecipada'),
					('Corporativo - Mensageria'),
					('Sulamerica teste'),
					('P20140924_001 - Atualização Tecnológica Fase III'),
					('Alocação Analista Negócio com PL/SQL'),
					('Flag de Tarifa Overlimit Pos Venda'),
					('P20151223_001 - Sustentação BI'),
					('Envio de Flag de Inibição de Tarifa – Pós Venda'),
					('P20140930_002 - Melhoria de Performance APIS TSYS'),
					('Transmissão de arquivos digitais das lojas'),
					('Treinamento e Consultoria para Elaboração de EFN'),
					('P20150518_001 - Parcelamento de Saldo (P20141003_001)'),
					('Intranet CSF'),
					('C20141013_001 - Consultoria UML utilizando Enterprise Architect'),
					('RFP Programa de Transformação de TI'),
					('Portal de condomínios'),
					('Gestão de Promoções'),
					('Alocação Consultor Arquitetura'),
					('Sustentação Corretor Web'),
					('P20141006_001 - Fábrica de Testes Makro - Projeto Zanthus'),
					('P20141111_001 - Gestão e Controle Embossing Online'),
					('B_CSF - Darlan Novaes da Silva Santos'),
					('A20141031_002 - B_CSF - Carmen Cecilia Pena Devesa'),
					('A20141031_003 - B_CSF - Leonardo Morato do Amaral Bertolini'),
					('A20141031_004 - B_CSF - Fabio Ricardo David'),
					('A20141031_005 - B_CSF - Fabio Gutierrez de Brito'),
					('A20141031_007 - NETSH - Kécyo Sacramento Barros'),
					('B_REN - Alexandre Fischer da Silva'),
					('A20141031_009 - SKY - Humberto Pimentel Bezerra'),
					('A20141031_010 - SKY - Thatiana Liz Santos Oliveira'),
					('WALM - Douglas Moraes Pereira'),
					('A20141031_012 - WALM - Rodrigo Picini'),
					('WALM - Thiago Julio Bovo Rodrigues'),
					('A20141031_014 - WILLIS - Caroline Aparecida de Melo Canto'),
					('A20141112_001 - B_CSF - Joaquim Jeunon Sousa'),
					('A20141112_002 - B_CSF - Gerson Eli Santos'),
					('P20141118_001 - Análise Promocional'),
					('NETSH - Osvaldo Martini Filho'),
					('A20141119_002 - WALM - Vitor Rossetto'),
					('P20141203_001 - App Prozperar'),
					('P20141027_001 - SGP - Sistema Gestão de Perecíveis'),
					('Sustentação - Gestão de Contratos SMART (Operação)'),
					('Inclusão de campo na proposta'),
					('P20141128_001 - Formulário de Leads - 2º Pacote'),
					('P20150101_001 - Desconto nos canais'),
					('C20130101_001 - Unidade Comercial - Verity'),
					('PA121112 - Projeto Administrativo'),
					('A20150128_001 - B_CSF_Silvia Kawasaki'),
					('X Adequação da Memória de Cálculo Verity'),
					('P20150226_001 - Migração Servidores 2012'),
					('Projeto Administrativo - Especiais'),
					('A20150309_001 - B_CSF - Caio Alexandre Fernandez de Agustini Farina'),
					('A20150302_001 - B_CSF - Ellen Cristina Sudré Sobrinho Oliveira'),
					('Sul América WorkSite - Sustentação'),
					('Prospecção - Pré-Venda'),
					('P20130912_002 - Melhorias Cadastro Positivo'),
					('Melhorias VeritySys'),
					('Solução de Gestão de contratos de TELECOM'),
					('Tratamento nos canais - Clientes Expurgados'),
					('P20130628_003 - Identificação de Cliente Expurgado'),
					('Verisys MC e Apontamentos'),
					('P20120906_001 - Automatização do Outbound'),
					('Novo Modelo de Autorizador'),
					('P20150420_001 - PopUp Seguros'),
					('Walmart_20150408_consultoria Vitor Rossetto'),
					('P20150330_001 - Migração do serviço de SMS Token para Nova PR'),
					('alocação Java Pleno TESTE'),
					('P20150430_001 - Consultoria Liferay_BNB'),
					('P20150502_001 - Cancelamento de Venda - BI'),
					('P20150318_001 - Gerador de E-mail Marketing - Envio de E-mail'),
					('P20150213_001 - Migração ERP - AX2009 para AX2012'),
					('P20150505_002 - ALELO - PV - Testes'),
					('P20150511_001 - PV - Projeto de Desenvolvimento Liferay'),
					('P20150511_002 - Termo Adesão - Pacote de Funcionalidades I'),
					('P20150514_001 - PV - Status Protocolo Portal'),
					('P20150514_002 - PV - APP Programa VIP - Telefônica'),
					('P20150514_003 - PV - Prestação de Serviços de BI'),
					('P20130313_001 - Cancelamento de Vendas'),
					('11052015_11 - B_CSF - Tiago Figueiredo Costa'),
					('P20140915_001 - Consulta automática SISBACEN'),
					('C20150120_001 - Consultoria em Arquitetura de Sistemas'),
					('P20140919_001 - Front End Corporativo'),
					('P20150315_001 - Gestão Testes Nova URA'),
					('P20150103_001 - Relatorio TAS Controle Operacoes'),
					('P20150409_001 - Simulador de CET no FUN'),
					('P20150418_001 - Solução CHAT'),
					('P20140829_001 - Solucao Multiplos Logins - FUN'),
					('P20140620_001 - Sustentação - Gerador de E-mail Marketing'),
					('P20141127_001 - PV - MecSasMov'),
					('Migração Recupera'),
					('P20141222_001 - Solução Boleto Manual'),
					('Novo Painel de Controle - Terra Empresas'),
					('Unidade Requisitos e Teste'),
					('Unidade Desenvolvimento'),
					('P20140331_002 - Sustentação - Smart'),
					('C20150528_001 - Consultoria Crédito'),
					('P20150528_001 - PV - Simulador CET'),
					('P20131203_003 - PV - Implementação Autorizador'),
					('P20150528_002 - PV - POC Comunicação Whatsapp'),
					('P20150529_001 - Melhorias Overlimit'),
					('PA20120206_002 - Projeto Infra'),
					('P20150609_001 - PV - APP Turbine sua Casa - VIVO'),
					('P20150612_001 - Nova Solução - Smart'),
					('P20131010_001 - PV - Alelo - Fábrica Funcional'),
					('P20130118_002 - Inclusão Automática Termo de Adesão'),
					('P20140305_002 - Evolução SASMOV'),
					('P20150618_001 - Portal - Nova Solução de Login'),
					('SIMULADOR - ANO 2016'),
					('P20150622_001 - PV - Portal de Notícias e Eventos'),
					('P20150630_001 - PV - APP SulAmérica'),
					('P20150630_002 - PV - Intranet Carrefour'),
					('P20150630_003 - PV - APP Carrefour'),
					('P20150703_001 - Beauty Club'),
					('P20150701_002 - Anexo do Projeto Marketing (Performance Promocional)'),
					('P20150701_001 - Update Base Item - GP - Produção e Homologação'),
					('SIMULACAO - PROJETO SISTEMA IMOBILIÁRIO'),
					('A20150701_001 - B_CSF - Washington de Souza Neris'),
					('P20150715_001 - Novo Portal - Área Não-Logada - Frente de Testes'),
					('P20150716_001 - Gestão de Configuração'),
					('P20150723_001 - PDV - Pré Aprovado Online'),
					('P20150727_001 - Cartão Atacadão'),
					('P20150727_002 - Migração Exceller'),
					('P20150728_001 - MOCK URA'),
					('P20150730_001 - Melhoria Controle AR'),
					('P20150730_002 - Internalizando o VPF - Frente de Testes'),
					('P20150423_001 - Sistema Imobiliario'),
					('P20150730_003 - Modificações Plano de Mídia'),
					('P20150731_001 - Flexibilidade Atendimento Ouvidoria'),
					('P20150731_002 - Intercâmbio'),
					('P20150806_001 - Integração de Ferramenta de Prevenção - Solução Completa'),
					('P20150806_002 - Melhorias SM - Ajustes Hierarquias e Parametrização'),
					('P20150807_001 - Unidade de Desenvolvimento'),
					('P20150811_001 - Nova alteração de limite no Portal'),
					('Cinemark - Einstein'),
					('P20150501_001 - Alteração Senha SM/AD - Nova Solução de Cobrança (P20140305_003)'),
					('P20150817_001 - Melhorias Crédito Pessoal para o Clock Work'),
					('P20150817_002 - Cadastro do Celular Seguro na Proposta'),
					('P20150817_003 - Opt-in permissão contato'),
					('P20150819_001 - Acompanhamento Piloto Gestão Promoções'),
					('P20150824_001 - PV - Gerador de E-mail Marketing - Melhorias'),
					('Gestão do Conhecimento'),
					('P20150826_001 - Parcelamento de Saldo Fase 2'),
					('P20150826_002 - Estruturação escritório de Campinas'),
					('P20150827_001 - Sustentação SQL Server'),
					('P20150831_002 - SulAmerica - Sustentação Canal de Vendas'),
					('P20150901_001 - Segunda Via de Fatura'),
					('P20150908_001 - Load Balance Paytrue'),
					('O20150909_001 - Sustentação Portal de Cartões'),
					('P20150922_001 - Fast Track - Exclusão Opção Nenhum'),
					('P20150922_002 - Fast Track - Cancelamento de propostas em Dados Mínimos'),
					('A20150916_001 - B_CSF - Cristina dos Santos Cardoso de Carvalho'),
					('TRIB OVERHEAD'),
					('P20151001_001 - PV - Criação de Workflows - Sharepoint'),
					('P20151005_001 - Alteração da Assinatura de e-mail do código de validação'),
					('P20151005_002 - Melhorias Prêmio Único Parcelado'),
					('P20151005_003 - Solução Upload Arquivos de Áudio'),
					('P20151007_001 - Novos Serviços LIFE'),
					('P20151007_002 - Migração de Portlets'),
					('P20151007_003 - Solução de Contingência - Conciliação'),
					('P20151008_001 - Consultoria Testes UAT'),
					('P20151008_002 - Solução PME'),
					('P20151027_001 - Consultoria BI para projeto E-commerce'),
					('P20151103_001 - Sustentação Aplicação Web'),
					('P20151109_001 - Pré aprovado Online - Fase 3'),
					('P20140305_002 - PV - Evolução SASMOV'),
					('P20151118_001 - Inclusão Link Revenda Seguros'),
					('P20151126_001 - Mobile CSF'),
					('P20151126_002 - Reestruturação de Endereço na Tsys'),
					('TEST MAKRO'),
					('Teste PROJETO IVAN'),
					('P20151210_001 - Consultoria - Especialista Sistemas e Canais'),
					('P20151210_002 - Abordagem Gestão de Configuração'),
					('P20151215_001 - Intranet Liferay'),
					('P20151215_002 - Plataforma SMS Front-Único'),
					('P20151215_003 - Telefone Identificado URA'),
					('P20151215_004 - Parametrizar Logo Front-Único'),
					('P20160104_001 - Plataforma SMS Front-Único - Fase 2'),
					('P20160105_001 - Monitor de Autorizações'),
					('P20160105_002 - PV - Hotsite Campanha'),
					('P20160105_003 - Regressão - melhorias arquitetura portlets Diebold'),
					('P20160112_001 - Evolução SASMOV - Frente de Testes'),
					('P20160112_002 - Gestão de Configuração - Portal'),
					('P20160117_001 - Security Manager - Token Permanente'),
					('P20160120_001 - Melhorias na abertura de Conta via internet'),
					('P20160122_001 - FastTrack - NFP - Adequação de Campos - Outbound'),
					('P20160202_001 - Sustentação Ambiente Certificação'),
					('P20151223_002 - SulAmérica WCF'),
					('A20151101_001 - B_CSF - Carmen Cecilia Pena Devesa'),
					('A20160101_001 - B_CSF - Consultoria VBA'),
					('A20151101_003 - B_CSF - Vander Braga Menezes'),
					('A20160201_001 - B_CSF - Gerson Eli Santos'),
					('A20160217_001 - Consultoria em Desenvolvimento Java'),
					('PA20160201_001 - Melhorias VeritySys'),
					('A20160101_002 - SEPHO - Jose Henrique Hino'),
					('A20151221_001 - B_CSF - Lilian Ramo de Souza Simioni'),
					('P20160223_001 - Sistema GERAR'),
					('P20160223_002 - Gerador de E-mail Marketing - Módulo de Peças Impressas'),
					('P20160223_003 - Implantação e Melhorias – Genesis'),
					('Projeto Willis - A*'),
					('P20160215_001 - Sustentação de Aplicações'),
					('P20160229_001 - Alelo - Automatização de Portais'),
					('A20141031_006 - B_CSF - Vander Braga Menezes*'),
					('P20160301_002 - Migração APP Auto'),
					('P20160301_001 - APP - Guru'),
					('P20160301_003 - IsyBuy'),
					('P20160304_001 - Alelo - Projeto Extrato Conta Empresa'),
					('P20160307_001 - Banco Original - Projeto de Fábrica de Testes'),
					('PA20160303_001 - Investimento Verity'),
					('PA20160308_001 - Entrevistas e Correção dos Testes'),
					('P20160309_001 - Cancelamento via Portal WSGate e EGSF'),
					('P20160314_002 - SMS Controle Total - Portal - Frente de Testes'),
					('P20160314_003 - Fábrica de Testes Cinemark'),
					('P20160314_001 - Novas implementações Novo Fluxo Proposta'),
					('P20160316_001 - Migração do portal para Liferay'),
					('P20160317_001 - War Room - Portal de Cartões'),
					('P20130912_007 - Fábrica de Teste Makro - Fase Operação'),
					('P20160318_001 - Migração de Portlets Portal para nova arquitetura'),
					('P20160318_002 - Abordagem - Garagem de Inovação'),
					('PA20160301_001 - Sustentação - Sistemas Internos'),
					('P20160321_001 - Fast-Track – Termo de Adesão no Cadastro de1ª Senha'),
					('P20160321_002 - Melhorias nos códigos de barras'),
					('O20140416_001 - CSF Sustentação - Suporte a Produção'),
					('P20160326_001 - Security Manager - Disponibilização de serviços para consumo'),
					('P20160404_001 - Alteração Active X - Mandate MasterCard'),
					('P20160407_001 - Security Manager - Disponibiliza Manutenção de Usuário'),
					('A20160426_001 - B_CSF - Janilson Lima Gomes'),
					('P20160424_001 - Portal - Lightbox Celular Seguro'),
					('P20160424_002 - Migração Nono Dígito'),
					('P20160429_001 - Adequações FUN para Mobile'),
					('P20160502_001 - Líder Projetos - Canais Web'),
					('P20160502_002 - Desenvolvimento em Liferay - Time & Material'),
					('P20160505_001 - Nono Digito - Centro Oeste'),
					('P20160505_002 - Melhorias URA Central e IW - Transferências - Frente de Testes'),
					('C20160516_001 - Consultoria Gestão Configuração'),
					('P20160516_001 - Garagem Inovação - Be Digital'),
					('P20160504_001 - Ofertas Fase 2 - Frente de Testes'),
					('P20160527_001 - Dremel Selector App'),
					('P20160527_002 - Expenses Report'),
					('P20160527_003 - Prestação de Serviço de Desenvolvimento .NET'),
					('P20160527_004 - Fábrica Desenvolvimento Genesis'),
					('P20160628_001 - Site Institucional - Liferay'),
					('P20160628_002 - Consultoria Liferay'),
					('P20160704_001 - Fast-Track - Melhoria - Bloqueio de Cartões'),
					('P20160624_001 - Testes na Loja Virtual da Sephora'),
					('P20160706_001 - Fast-Track - Termo de Escolha de Senha'),
					('P20160709_001 - Monitoramento de Serviços PR'),
					('P20160722_001 - Melhorias Parcele Fácil'),
					('P20160705_001 - Implantação Cerberon'),
					('P20160727_001 - Evolução Webclaim e Marketplace - Concepção'),
					('P20160609_001 - BI Demanda Indireta'),
					('P20160726_001 - Data Layer - Portal'),
					('P20160729_001 - Precificação e Integração de Contrato'),
					('P20160718_001 - Consultoria em Analise de Sistemas'),
					('P20160805_001 - Cartão Gold'),
					('P20160805_002 - Clock Work'),
					('P20160809_001 - Indicadores IAS'),
					('P20160819_001 - Novo Rabicho'),
					('P20160823_001 - Controle AR - Consulta Faixa de CEP'),
					('P20160823_002 - Melhorias Security Manager'),
					('P20160831_001 - Migração Portal Liferay Canadá'),
					('P20160831_002 - Sales Process'),
					('P20160830_001 - Programa de Reconhecimento de Profissionais'),
					('P20160830_002 - Melhorias e Perfil de Crédito Pessoal'),
					('P20160915_001 - Ura Clock Work - Frente De Testes'),
					('P20160915_002 - Cadastro Intermediários'),
					('P20160905_001 - ClockWork - Integrador'),
					('O20161001_001 - Sustentação Cadastro Positivo'),
					('P20161004_001 - Homologação do Clock Work - Equipe de Crédito'),
					('P20161010_001 - Normativa Correios'),
					('P20161010_002 - Clock Work - Fase 2'),
					('P20161010_003 - Unificar Transações de Encargos'),
					('P20161010004 - Integração de Ferramenta de Prevenção - Solução Completa'),
					('P20161019_001 - Novas Implementações Embossing Online'),
					('P20161019_002 - Ajustes Serviços de Cobrança'),
					('P20161020_001 - BI Demanda Indireta'),
					('P20161021_001 - Piloto do Processo QA CSF'),
					('P20161101_001 - Elaboração de Programas - Plataforma LIFERAY'),
					('P20161101_002 - Crédito Pessoal (FUN e PR)'),
					('P20161101_003 - Portal - Fast Track - 1º Acesso e M.Site'),
					('P20161103_001 - Proposta com Voz'),
					('P20170302001 - Pós Venda no Tablet'),
					('P20170309_001 - Gestão de Configuração - Integração Continua'),
					('P20170309_002 - Gestão de Configuração - Migração repositório'),
					('P20170316001 - Medida Provisória Bacen'),
					('P20170120_001 - Consultoria Serviços PR para Desenvolvimento APP'),
					('P20150821_001 - Sustentação SQL Server'),
					('P20150824_001 - Gerador de E-mail Marketing - Melhorias'),
					('P20160321_002 - Boleto Registrado'),
					('P20160603_001 - Implementação de Conteúdo - Portal de Cartões'),
					('P20160727_001 - Assessoria e Consultoria em TI'),
					('A20160822_001 - Consultoria em Infraestrutura - Oclock'),
					('P20161011_002 - Clock Work - Fase 2'),
					('A20161110_001 - Consultoria em Desenvolvimento Java'),
					('P20161111_002 - APP Tablet Clock Work'),
					('P20161117_001 - Impressão Fatura Atual TAS'),
					('P20161117_002 - Seguros Não Cartonistas'),
					('P20170309_003 - Gestão de Configuração - Atacadão'),
					('P20161111_002 - APP Tablet Clock Work'),
					('P20161114_002 - Homologação do Clock Work - Equipe de Crédito - Fase 2'),
					('P20161125_001 - APP - Desbloqueio de Cartão - Envio de dados para PayTrue'),
					('P20161126_002 - Lista de Bancos com DCC'),
					('A20161201001 - Prestação de Serviços de TI - Arquitetura'),
					('P20161214001 - Portal Clock Work'),
					('A20170102_001 - Desenvolvimento Java Sephora'),
					('P20170109001 - Consultoria PR para desenvolvimento APP - Fase 2'),
					('P20170109002 - Fábrica de Massas CSF'),
					('P20170112001 - Clock Work - Fase 3'),
					('P20170113001 - Cadastro Positivo na iniciação de Crédito'),
					('P20170120001 - Consultoria Serviços PR para Desenvolvimento APP'),
					('P20170120_002 - Consultoria em Desenvolvimento'),
					('P20170327001 - Medida Provisória - Portal de Cartões'),
					('P20170301_001 - MuleSoft'),
					('P20161019_001 - Novas Implementações Embossing Online'),
					('P20170404_001 - Cadastro Online'),
					('P20170405_001 - Melhorias Ambiente HSM'),
					('P20170404_002 - Consultoria em Arquitetura de Sistemas - PR'),
					('A20170410_001 - Consultoria em Desenvolvimento Java'),
					('P20170411_001 - Novas implementações Integrador C++'),
					('O20140416_003 - CSF Sustentação - Release TSYS Abril/2017'),
					('O20140416_002 - CSF Sustentação - GMUD'),
					('P20170425_001 - Homologação do Parcelamento de Saldo para Funcionário'),
					('P20170428001 - Clock Work - Fase 4'),
					('P20170425_002 - Homologação do Portal Clock Work'),
					('P20170509001 - Clock Work Homologação - Fase 3'),
					('P20170515001 - Farmacovigilância - APP'),
					('O20140416_004 - CSF Sustentação - Acompanhamento Windows 2012'),
					('O20140416_005 - CSF Sustentação – Acompanhamento Instalação de patch Windows para “Wanna Cry”'),
					('O20140416_006 - CSF Sustentação – Acionamento pela equipe de N2 e GDN'),
					('P20170515002 - Envio de Certificado por E-mail'),
					('P20170530_001 - Atendimento Soluções Mobile como Integrador'),
					('O20140416_007 - CSF Sustentação - Plantão Presencial Dia dos Namorados')

		INSERT INTO [dbo].[tbCompetencia]
				   (nmCompetencia)
			 VALUES
				   ('Desenvolvimento'),
				   ('Profundidade'),
				   ('Planejamento'),
				   ('Execução e entrega'),
				   ('Pessoas'),
				   ('Comercial'),
				   ('Financeiro')

		INSERT INTO [dbo].[tbProva]
				   (nmProva)
			 VALUES
				   ('Prova prática'),
				   ('Prova teórica'),
				   ('Dinamica de grupo')

		INSERT INTO [dbo].[tbSituacaoAtual]
				   (nmSituacaoAtual)
			 VALUES
				   ('Cursando'),
				   ('Concluido'),
				   ('Interrompido')

		INSERT INTO [dbo].[tbTpStatus]
				   ([nmTpStatus])
			 VALUES
				   ('Candidato'),
				   ('Vaga')

		INSERT INTO [dbo].[tbFuncionario]
					([nmFuncionario])
			 VALUES
					('Adalberto Monteiro Junior'),
					('Adriano Patrício de Oliveira'),
					('Adriano Sciorilli'),
					('Alessandra da Silva Ribeiro'),
					('Alexandre Genka'),
					('Alexandre Teixeira Conceicao'),
					('Alexandro Barsi'),
					('Andre de Fazzio Posman'),
					('Andre Vitor Iackowski G Pietro'),
					('Andrea Fernandes dos Reis'),
					('Andrey Ryuki Imaguma'),
					('Ariel Nogueira dos Santos'),
					('Arthur Teixeira da Silva'),
					('Augusto dos Santos Marques'),
					('Barbara Hansen de Palma'),
					('Bruna Biontino Bezerra'),
					('Bruna Maciel Costa'),
					('Bruno Raminelli'),
					('Carlos Décio de Carvalho'),
					('Carmen Cecilia Pena Devesa'),
					('Claudio Barbosa Alozen'),
					('Cleber Teixeira Gomes da Cruz'),
					('Cristiane de Almeida'),
					('Cristiane Oliveira Vilar'),
					('Cristiano de Moraes'),
					('Dalmo Jose Santos'),
					('Daniel Ferreira do Valle'),
					('Danilo Novais de Oliveira'),
					('Diego Santos Franco'),
					('Diego Simezo Maeda'),
					('Diogo Ferreira Lopes'),
					('Edneia Nunes da Silva Sales'),
					('Edson Geraldo Pereira Maciel'),
					('Endrew Rodrigues Muller'),
					('Erick Cesar França Silva'),
					('Euller da Silva Araujo'),
					('Fabio Signore Arruda'),
					('Fabio Vilani Peres'),
					('Fernando Florencio de Oliveira'),
					('Fernando Honorio Fernades'),
					('Filipe Delgado dos Reis'),
					('Flavia da Silva Negreiros'),
					('Gabriela Candida do Nascimento'),
					('Gerson Eli Santos'),
					('Graziele Ferreira Barboza'),
					('Guilherme de Oliveira'),
					('Gustavo Alves dos Santos Silva'),
					('Henrique Baptista Testa'),
					('Iago Alves Melo'),
					('Igor Cunha de Almeida'),
					('Jefferson Anderson Torres'),
					('Jefferson da Silva Reis'),
					('Jeffersonn Lucas Monteiro Barboza'),
					('João Eduardo Bianchini Junior'),
					('Joaquim Jeunon Sousa'),
					('Jose Henrique Hino'),
					('Jose Pereira'),
					('Juliana Almeida Alves de Godoy'),
					('Juliana Kahan'),
					('Laerccius Moraes Santana'),
					('Lais Oliveira Senario'),
					('Leandro Yoshikay de SantAnna'),
					('Leonardo Ramos'),
					('Leonardo Silva Miranda'),
					('Lilian Ramo de Souza Simioni'),
					('Lucas Alves Benn Pereira de Oliveira'),
					('Lucas de Souza Azevedo'),
					('Lucas Hiroaki Uno Nishimura'),
					('Lucas Raposo de Andrade'),
					('Luis Gustavo Ramos'),
					('Luiz Eduardo Rovaris'),
					('Luiz Henrique Lochetti'),
					('Manoel Rodrigues da Silva Junior'),
					('Marcelo Santos do Nascimento'),
					('Marcio Akira Kusama'),
					('Marcos Vinicius Pinto'),
					('Maria Jose Felix Pereira Leal'),
					('Mariana Serrano Martini'),
					('Mateus Dias Pardinho'),
					('Melissa Silva Sales'),
					('Michela de Oliveira Senario'),
					('Natacha Honda Pepeliascov'),
					('Natalia Vitoria Ono Morazani'),
					('Odir Lopes Pinheiro'),
					('Paola Oliveira Farias'),
					('Paulo Eduardo Jesus de Carvalho'),
					('Pedro Henrique Chueri Olejnik'),
					('Perciliana Aparecida de Oliveira'),
					('Priscila Fernanda Becker'),
					('Rafael Campos Arraes'),
					('Rafael Feo'),
					('Rafaela Barbosa da Silva'),
					('Raphael Thaumaturgo Molnar'),
					('Raul Marciano Ferreira'),
					('Renan Samuel Nucci'),
					('Renan Silva Yoshida'),
					('Renata Pierina de Oliveira'),
					('Rene Doern'),
					('Roberto Francelino da Silva Junior'),
					('Rodrigo Ribeiro do Nascimento'),
					('Roger Adalberto Mota Fernandes'),
					('Samiris Alvaro Gomes Batista'),
					('Silmara Pereira Buchud Silva'),
					('Silvia Miyuki Matsumaru'),
					('Stephen Rodrigues Knupfer'),
					('Suelen Batista da Silva'),
					('Taiama Mariane Marinho Santos'),
					('Taty Tozzi de Moraes'),
					('Thamires Pinho de Miranda'),
					('Thiago de Moraes Silva'),
					('Tiago Cidre Rodrigues'),
					('Vera Tavares'),
					('Victor Rocha Gomes da Silva'),
					('Vinicius Ferlin'),
					('Vinicius Gabriel Bomfim Ribeiro'),
					('Vitor Rossetto'),
					('Vitor Tadashi Uno Nishimura'),
					('Washington de Souza Neris'),
					('Willian Joddy Kaneko'),
					('Wilson Roberto Baptista'),
					('Wylberth Gomes da Silva'),
					('Yuri Bueno De Mesquita Da Silva')

		INSERT INTO [dbo].[tbStatus]
				   (idStatus, nmStatus, tpCss, idTpStatus)
			 VALUES
				   (1,'Ativo', '#2ECC71', 2),
				   (2,'Fechado', '#ed6f02', 2),
				   (3,'Cancelado', '#CF000F', 2),
				   (4,'Pendente', '#02b4ea', 2),
				   (5,'Candidatura', '#03C9A9', 1),
				   (6,'Candidato em análise', '#e67e22', 1),
				   (7,'Candidato aprovado', '#2ECC71', 1),
				   (8,'Candidato reprovado', '#CF000F', 1),
				   (9,'Gerar proposta', '#03C9A9', 1),
				   (10,'Proposta gerada', '#03C9A9', 1),
				   (11,'Proposta aprovada', '#2ECC71', 1),
				   (13,'Proposta recusada', '#CF000F', 1),
				   (14,'Candidato recusou proposta', '#F9690E', 1),
				   (15,'Contratado', '#2ECC71', 1),
				   (17,'Cancelado', '#CF000F', 1),
				   (18,'Reprovado', '#CF000F', 2),
				   (27,'Vaga nova', '#F9690E', 2),
				   (29,'Sem vaga', '#808080', 1)

		INSERT INTO [dbo].[tbStatusDisponivel]
				   (idStatus, idStatusDisponivel, nmOpcao, nmClasse)
			 VALUES
				   (5,6,'Enviar para análise','class="glyphicon fa fa-check fa-lg"'),
				   (6,7,'Aprovar candidato','class="fa fa-check fa-lg"'),
				   (6,8,'Reprovar candidato','class="fa fa-times fa-lg"'),
				   (9,10,'Gerar proposta','class="fa fa-pencil fa-lg"'),
				   (10,11,'Aprovar proposta','class="fa fa-check fa-lg"'),
				   (10,13,'Reprovar proposta','class="fa fa-times fa-lg"'),
				   (11,14,'Candidato recusou proposta','class="fa fa-times fa-lg"'),
				   (11,15,'Contratar candidato','class="fa fa-check fa-lg"'),
				   (13,10,'Refazer proposta','class="fa fa-refresh fa-lg"'),
				   (14,10,'Refazer proposta','class="fa fa-refresh fa-lg"'),
				   (1,3,'Cancelar','class="fa fa-ban fa-lg"'),
				   (1,2,'Fechar','class="fa fa-trash-o fa-lg"'),
				   (4,27,'Aprovar','class="fa fa-check fa-lg"'),
				   (4,18,'Reprovar','class="fa  fa-times fa-lg"'),
				   (27,1,'Divulgar','class="fa fa-check fa-lg"'),
				   (27,3,'Cancelar','class="fa fa-ban fa-lg"')

		INSERT INTO [dbo].[tbStatusFuturo]
				   ([idStatus]
				   ,[idStatusFuturo])
			 VALUES
				   (7,6),
				   (7,9)

		INSERT INTO [dbo].[tbTipoCurso]
				   ([nmTipoCurso])
			 VALUES
				   ('Formação Escolar Fundamental (1° grau) e Média (2° grau)'),
				   ('Curso Técnico - Médio (2º Grau)'),
				   ('Graduação'),
				   ('Pós-graduação – Especialização'),
				   ('Pós-graduação – MBA'),
				   ('Pós-graduação – Mestrado'),
				   ('Pós-graduação – Doutorado'),
				   ('Não informado')

		INSERT INTO [dbo].[tbCargoSenioridade]
				   (idCargo, idSenioridade, vlMinSalario, vlMaxSalario,dsPreFormacaoAcademica,
				   dsPrePerfilComportamental, dsPrePerfilTecnico)
			 VALUES
					(1,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(1,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(1,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(2,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(2,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(2,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(3,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(3,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(3,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(4,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(4,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(4,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(5,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(5,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(5,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(6,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(6,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(6,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(7,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(7,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(7,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(8,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(8,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(8,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(9,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(9,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(9,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(10,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(10,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(10,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(11,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(11,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(11,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(12,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(12,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(12,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(13,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(13,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(13,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(14,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(14,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(14,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(15,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(15,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(15,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(16,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(16,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(16,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(17,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(17,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(17,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(18,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(18,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(18,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(19,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(19,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(19,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(20,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(20,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(20,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(21,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(21,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(21,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(22,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(22,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(22,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(23,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(23,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(23,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(24,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(24,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(24,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(25,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(25,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(25,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(26,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(26,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(26,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(27,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(27,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(27,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(28,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(28,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(28,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(29,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(29,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(29,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(30,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(30,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(30,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(31,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(31,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(31,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(32,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(32,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(32,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(33,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(33,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(33,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(34,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(34,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(34,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(35,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(35,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(35,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(36,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(36,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(36,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(37,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(37,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(37,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(38,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(38,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(38,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(39,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(39,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(39,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(40,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(40,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(40,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(41,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(41,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(41,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(42,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(42,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(42,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(43,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(43,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(43,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(44,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(44,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(44,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(45,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(45,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(45,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(46,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(46,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(46,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(47,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(47,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(47,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(48,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(48,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(48,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(49,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(49,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(49,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(50,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(50,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(50,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(51,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(51,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(51,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(52,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(52,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(52,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(53,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(53,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(53,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(54,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(54,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(54,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(55,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(55,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(55,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(56,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(56,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(56,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(57,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(57,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(57,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(58,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(58,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(59,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(59,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(59,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(60,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(60,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(60,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(61,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(61,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(61,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(62,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(62,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(62,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(63,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(63,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(63,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(64,1,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(64,2,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)'),
					(64,3,1000.00,2000.00,'Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados.','Boa oratória que transmita tranquilidade e confiança.','Base sólida em computação (Algoritmos e Estruturas de Dados e Orientação a Objetos)')


		INSERT INTO [dbo].[tbFuncionalidade]
				   (idFuncionalidade,nmFuncionalidade, url)
			 VALUES
					(1,'Aprovar/Reprovar vaga','vaga/aprovar'),
					(2,'Consultar vaga','vaga/consultar'),
					(3,'Solicitar vaga','vaga/solicitar'),
					(16,'Criar perfil','usuario/perfil/gerenciar'),
					(17,'Cadastrar candidato','candidato/cadastrar'),
					(18,'Consultar candidato','candidato/consultar'),
					(22,'Criar usuário','usuario/gerenciar'),
					(23,'Aprovar/Reprovar proposta','colocarUrlAqui'),
					(24,'Informar avaliador','colocarUrlAqui'),
					(25,'Aprovar/Reprovar candidato','candidato/aprovar'),
					(26,'Gerar proposta','colocarUrlAqui'),
					(27,'Analisar candidato','colocarUrlAqui'),
					(28,'Refazer proposta','colocarUrlAqui'),
					(29,'Cancelar vaga','colocarUrlAqui'),
					(30,'Fechar vaga','colocarUrlAqui'),
					(31,'Editar vaga','colocarUrlAqui'),
					(32,'Editar candidato','candidato/editar/*'),
					(34,'Informar data contato','colocarUrlAqui'),
					(35,'Aprovar vaga','colocarUrlAqui')

	INSERT INTO [dbo].[tbPerfil]
				   (nmPerfil)
			 VALUES
					('Administrador')

	INSERT INTO [dbo].[tbPerfilFuncionalidade]
				   (idPerfil, idFuncionalidade)
			 VALUES
					(1, 16),
					(1, 22)

	INSERT INTO [dbo].[tbUsuario]
				   (idPerfil, idFuncionario, senha ,nmUsuario, email, flPrimeiroAcesso, ativo)
			 VALUES
					(1, 50, 'admin', 'dmVyaXR5QDEyMw==' ,'admin@verity.com.br', 1, 1)
	
	COMMIT TRANSACTION;
 
    PRINT 'Sucesso na execução do script ['+ @nomeScript +']'
END TRY
BEGIN CATCH
		IF @@TRANCOUNT > 0
			 ROLLBACK TRANSACTION;
             
 		DECLARE @errorNumber INT;
		SET @errorNumber  = ERROR_NUMBER();
		DECLARE @errorLine INT;
		SET @errorLine = ERROR_LINE();
		DECLARE @errorMessage NVARCHAR(4000);
		SET @errorMessage = ERROR_MESSAGE();
		DECLARE @errorSeverity INT;
		SET @errorSeverity = ERROR_SEVERITY();
		DECLARE @errorState INT;
		SET @errorState = ERROR_STATE();
      
		PRINT 'ERRO na execução do script. [' + @nomeScript + ']'
		PRINT 'Número do erro: [' + CAST(@errorNumber AS VARCHAR(10)) + ']';
		PRINT 'Número da linha: [' + CAST(@errorLine AS VARCHAR(10)) + ']';
		PRINT 'Descrição do erro: [' + @errorMessage + ']';
 
		RAISERROR(@errorMessage, @errorSeverity, @errorState);
END CATCH