SELECT * FROM Livro

SELECT * FROM Cd

DROP TABLE Livro

CREATE TABLE Livro(
codLivro INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
titulo VARCHAR(50) NOT NULL,
autor VARCHAR(50) NOT NULL,
editora VARCHAR(50) NOT NULL,
numeroPa INT NOT NULL
)